version: 2.1

parameters:
  always-continue:
    type: string
    default: ""
jobs:
  build-code:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Building code"
  lint:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Running linting"

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Running tests"

workflows:
  s1-workflow:
    jobs:
      - lint # use the shared lint job.
      - test # use the shared test job.
      - build-code