version: 2.1

parameters:
  always-continue:
    type: string
    default: ""

jobs:
  build-docs:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Building docs"
  lint:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Running linting"

workflows:
  s2-workflow:
    jobs:
      - lint # use the shared lint job.
      - build-docs